apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-portal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Gi-v/platform-one
    targetRevision: HEAD
    path: portal/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
