server:
  dev:
    enabled: true
    devRootToken: "root"
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
injector:
  enabled: false
ui:
  enabled: true
  serviceType: ClusterIP
